my_portfolio_website/urls.py
#<--- My Portfolio Website - Imported Packages List ----
from django.contrib import admin
from django.urls import path,include
#</--- My Portfolio Website - Imported Packages List ----



#Admin Site Header Name
admin.site.site_header = "My Portfolio Admin"
#Admin site Title
admin.site.site_title = "My Portfolio Admin Portal"
#Admin site Index title
admin.site.index_title = "Welcome to My Portfolio Portal"





#---My Portfolio Website Admin and Data Management URL List ---
urlpatterns = [
    #Url for Admin Site
    path('admin/', admin.site.urls),

    #Url for my_portfolio_website_app configuration
    path('', include('my_portfolio_website_app.urls')),
]

#/---My Portfolio Website Admin and Data Management URL List ---

my_portfolio_website_app/urls.py
#<--- My Portfolio Website - Imported Packages List ----

#------Django Internal Packages-----
from django.contrib import admin
from django.urls import path
#/------Django Internal Packages-----

#<-------- importing view from my_portfolio_website_app -------------
from my_portfolio_website_app import views
#</-------- importing view from my_portfolio_website_app -------------

#</--- My Portfolio Website - Imported Packages List ----

#App Name in the project
app_name='my_portfolio_website_app'



#<------------------------ Project URLS --------------------------------------

urlpatterns = [

#<------ Authentication URLS--------------------

    #Url for user_login view
    path('login',views.user_login,name='login'),

    #Urls for register view
    path('register',views.register,name='register'),

    #Url for logout view
    path('logout',views.log_out,name='logout'),

#<------ Authentication URLS--------------------


    #Url for about view 
    path('',views.about,name='about'),

    #Url for portflio view
    path('portfolio',views.portfolio,name='portfolio'),

    #Url for contact view
    path('contact',views.contact,name='contact'),

    #Url for Contcat form submit view
    path('contact_form_submit',views.contact_form_submit,name='contact_form_submit'),

    #Url for all_data view
    path('all_data',views.all_data,name='all_data'),

    #Url for users view
    path('users',views.users,name='users'),

#</------------------------ Project URLS -------------------------------------

]

my_portfolio_website_app/models.py
#<--- My Portfolio Website - Imported Packages List ----

#<------Django Internal Packages-----
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
#</------Django Internal Packages-----

#</--- My Portfolio Website - Imported Packages List ----

# Create your models here.

#Contact Form Model
class ContactForm(models.Model):
    #Total Fields : 5
    #------Contact form Table Fields------

    #This field store Full Name 
    full_name = models.CharField(max_length=300,blank=True)
    #This field store Email ID
    email_id = models.CharField(max_length=300,blank=True)
    #This field store Contact Number 
    contact_number = models.CharField(max_length=300,blank=True)
    #This field store Message 
    message = models.TextField(max_length=3000,blank=True)
    #This field store Date & Time at which form is submitted
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.pk) #Return Primary Key

    class Meta:
        verbose_name_plural = "Contact Form Data"
        verbose_name = "Contact Form"





#CustomUser Model
class CustomUser(AbstractUser):
    #Total Fields : 3
    #Total Roles : 3
    #------Custom User Table Fields------
    '''Overrides the custom django user model'''
    # Datafields
    SUPER_ADMIN = 1
    ADMIN = 2
    NORMAL_USER = 3
    ROLE_CHOICES = (  
      (SUPER_ADMIN,'super_admin'),
      (ADMIN,'admin'),
      (NORMAL_USER,'normal_user'),
    )
    #This field store User's Role
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES,default=NORMAL_USER)
    #This field store User's Name
    name = models.CharField(max_length=264, blank='True')

my_portfolio_website_app/views.py
#<--- My Portfolio Website - Imported Packages List ----


#<------Django Internal Packages-----
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
#</------Django Internal Packages-----

#<------ External Installed Packages -----

#</------ External Installed Packages -----


#<------ My Portfolio Website Internal Project Packages -----
from my_portfolio_website_app.models import ContactForm,CustomUser
#</------ My Portfolio Website Internal Project Packages -----


#</--- My Portfolio Website - Imported Packages List ----


#Create your views here.

#<---------------------- Authentication Views --------------------------------------

#User Login View 
def user_login(request):
    """Logs in a user if the credentials are valid and the user is active,
    else redirects to the same page and displays an error message."""
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('my_portfolio_website_app:all_data'))
        else:
            return render(request,'my_portfolio_website_app/registration/login.html',{'error_message': 'Username or Password Incorrect!'})
    else:
        return render(request,'my_portfolio_website_app/registration/login.html')



#User Register view
def register(request):
    """Registers a user"""
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password != confirm_password:
            return render(request,'my_portfolio_website_app/registration/register.html',{'error_message':'Password Not Match!'})
        if CustomUser.objects.filter(username=username).exists():
            return render(request,'my_portfolio_website_app/registration/register.html',{'error_message':'Username already exist!'})
        else:
            user = CustomUser.objects.create(username=username, password= make_password(password),role=2)
            login(request,user)
            return HttpResponseRedirect(reverse('my_portfolio_website_app:all_data'))
    else:
        return render(request,'my_portfolio_website_app/registration/register.html')


#Logout View
def log_out(request):
    """User get logout from the session"""
    logout(request)
    return HttpResponseRedirect(reverse('my_portfolio_website_app:login'))


#</---------------------- Authentication Views --------------------------------------


#<-------------------------- Page Render view --------------------------------------

#about page view
def about(request):
    """This view render about.html page
    parameters: HttpRequest
    return: nothing  """
    return render(request,'my_portfolio_website_app/about.html')


#Portfolio Page view
def portfolio(request):
    """This view render portfolio.html page
    parameters: HttpRequest
    return: nothing  """
    return render(request,'my_portfolio_website_app/portfolio.html')


#Contact Page View
def contact(request):
    """This view render contact.html page
    parameters: HttpRequest
    return: nothing  """
    return render(request,'my_portfolio_website_app/contact.html')

#Contact Form Data Submit form view
def contact_form_submit(request):
    """This view take post method and submit form details 
        by creating ContactForm Model object
    parameters: HttpRequest
    return: if form data submit successfully then 
            HttpResponseRedirect to page contact.html  """
    if request.method == "POST":
        full_name = request.POST['full_name']
        email_id = request.POST['email_id']
        contact_number = request.POST['contact_number']
        message = request.POST['message']
        ContactForm.objects.create(full_name=full_name,
                                   email_id=email_id,
                                   contact_number=contact_number,
                                   message=message
                                   )
    return HttpResponseRedirect(reverse('my_portfolio_website_app:contact'))



#All Data View
@login_required(login_url='/login')
def all_data(request):
    """This view render all_data.html page
    parameters: HttpRequest
    return: contact_data  """
    contact_data = ContactForm.objects.all()
    data = {'contact_data':contact_data}
    return render(request,'my_portfolio_website_app/all_data.html',data)


#User Data View
@login_required(login_url='/login')
def users(request):
    """This view render users.html page
    parameters: HttpRequest
    return: users  """
    users = CustomUser.objects.all()
    data = {'users':users}
    return render(request,'my_portfolio_website_app/users.html',data)

#</-------------------------- Page Render view --------------------------------------

my_portfolio_website_app/templates/my_portfolio_website_app/about.html
{% extends 'my_portfolio_website_app/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
        
        .img-container img {
            border-radius: 50%;
            margin-bottom: 2rem;
        }

        .img-container {
            margin-top: 2rem;
        }

        .personal {
            padding: 3rem;
        }

        .detail {
            padding: 3rem;
        }
        .detail i {
            margin-right: 1rem;
            color: #15aabf;
        }

        b {
            padding-right: 10px;
        }

        .card {
            margin-top: 6rem;

        }

        ul {
            position: relative;
            right: 0;
        }

        .useful_link a {
            color: #ccc;
            margin: 1rem;
        }

        .useful_link a:hover {
            color: #000;
        }

        .profile_name h1,
        h5 {
            margin: 1rem;
        }
    </style>
    {% endblock stylesheets %}
    
    
    {% block headscript %}
    {% endblock headscript %}


{% block content %}


    <div class="container">
        <div class="col-sm-12">
            <div class="card shadow-lg p-3 mb-5 bg-white rounded">
                <div class="row ">
                    <div class="img-container mx-auto">
                        <img src="{% static 'my_portfolio_website_app/images/profile.png' %}">
                    </div>

                </div>
                <div class="row align-self-center">
                    <div class="profile_name text-center">
                        <h1>Tanmay Hatkar</h1>
                        <h5>I'm Front End Developer</h5>
                        <div class="useful_link ml-auto">
                            <center>
                                <a href="#"><span class="fab fa-github fa-2x"></span></a>
                                <a href="#"><span class="fab fa-linkedin fa-2x"></span></a>
                            </center>
                        </div>
                    </div>
                </div>
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-6 personal">
                            <h3 style="font-weight: bold">Personal Details</h3>
                            <p>Hye, I’m Johnathan Doe residing in this beautiful world. I create websites and mobile apps with great UX and UI design. I have done work with big companies like Nokia, Google and Yahoo. Meet me or Contact me for any queries. One Extra line for filling space. Fill as many you want.Duis sed odio sit amet nibh vulputate cursus a sit amet mauris. Morbi accumsan ipsum velit. Nam nec tellus a odio tincidunt auctor a ornare odio.</p>
                        </div>
                        <div class="col-md-6 detail">
                            <p><i class="far fa-user-circle"></i><b>Name:</b> Tanmay </p>
                            <p><i class="fas fa-phone"></i><b>Phone:</b> 9875612344</p>
                            <p><i class="fas fa-envelope"></i><b>Email:</b> tanmay.hats@gmail.com</p>
                            <p><i class="far fa-calendar-alt"></i><b>Date Of Birth:</b> 14-03-1997</p>
                            <p><i class="fas fa-map-marker-alt"></i><b>Address:</b> Mumbai Suburbs</p>
                            <p><i class="fas fa-code"></i><b>Language:</b> Python,HTML</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
{% endblock %}

my_portfolio_website_app/templates/my_portfolio_website_app/all_data.html
{% extends 'my_portfolio_website_app/base1.html' %}
{% load static %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}


{% block content %}

<h3>All Data</h3>
<hr>
<div>
    <table id="my_table" class="display" style="width:  100%;text-align: center;">
        <thead>
            <tr>
                <th>Sr. No</th>
                <th>Full Name</th>
                <th>Email Id</th>
                <th>Contact</th>
                <th>Message</th>
            </tr>
           
        </thead>
        <tbody>
            {% for data in contact_data %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ data.full_name }}</td>
                <td>{{ data.email_id }}</td>
                <td>{{ data.contact_number }}</td>
                <td>{{ data.message }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}



{% block script %}
{% endblock  %}



{% block extrascript %}
{% endblock extrascript %}

my_portfolio_website_app/templates/my_portfolio_website_app/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>My Portfolio</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0-4/css/all.css">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block stylesheets %}
    {% endblock stylesheets %}
    
    
    {% block headscript %}
    {% endblock headscript %}
    
    <style>
        body {
            background-color: #E8E8E8;
        }
    </style>
    
</head>

<body>

    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
            <a class="navbar-brand"><b>My Portfolio</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_portfolio_website_app:about' %}">About</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% static 'my_portfolio_website_app/resume/TYBScITSyllabus.pdf' %}" download>Resume</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_portfolio_website_app:portfolio' %}">Portfolio </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_portfolio_website_app:contact' %}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    
    {% block script %}
    {% endblock %}

</body>

</html>

my_portfolio_website_app/templates/my_portfolio_website_app/base1.html
<!DOCTYPE html>
<html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>My Portfolio</title>

    <style>
        #colmn {
            width: 1000px;
        }

        thead input {
            width: 100%;
        }
    </style>

    {% block stylesheets %}
    {% endblock stylesheets %}

    {% block headscript %}
    {% endblock headscript %}

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'my_portfolio_website_app/assets/css/style.css' %}">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href=" https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.5/css/fixedHeader.dataTables.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper">
        <!-- SIDEBAR  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4>My Portfolio Data Manager</h4>
            </div>

            <ul class="list-unstyled components">
                {% with url_name=request.resolver_match.url_name %}
                <li class="{% if url_name == 'all_data' %}active {% endif %}">
                    <a href="{% url 'my_portfolio_website_app:all_data' %}">All Data</a>
                </li>
                <li class="{% if url_name == 'users' %}active {% endif %}">
                    <a href="{% url 'my_portfolio_website_app:users' %}">Users</a>
                </li>
                <li>
                    <a href=""></a>
                </li>
                {% endwith %}
                <!--
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Leads Status</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="All.html">All</a>
                        </li>
                        <li>
                            <a href="new%20base.html">Pending</a>
                        </li>
                        <li>
                            <a href="InProcess.html">In Process</a>
                        </li>
                        <li>
                            <a href="Rejected.html">Rejected</a>
                        </li>
                    </ul>
                </li>
-->

            </ul>
            <ul class="list-unstyled CTAs">

                <li>
                    <a href="{% url 'my_portfolio_website_app:logout' %}" class="btn" style="background-color: #6d7fcc">
                        <font color="#fff">Logout</font>
                    </a>
                </li>

            </ul>
        </nav>
        <!--SIDEBAR ENDS HERE-->

        <!-- PAGE CONTENT  -->
        <div id="content">
            <div class="container-fluid">
                <button type="button" id="sidebarCollapse" class="btn" style="background-color: #7386D5;color: #fff">
                    <i class="fas fa-align-left"></i>
                </button>
                <hr>
                {% block content %}
                {% endblock %}

            </div>
        </div>


    </div>

    {% block script %}
    {% endblock  %}

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!--jQuery-->
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>


    {% block extrascript %}
    {% endblock extrascript %}
    
    <script type="text/javascript">
        $(document).ready(function() {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function() {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

    <script>
        $(document).ready(function() {
            $('#my_table').DataTable();
        });
    </script>

</body>

</html>

my_portfolio_website_app/templates/my_portfolio_website_app/contact.html
{% extends 'my_portfolio_website_app/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    .box {
        margin-top: 6rem;

    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;
         !importatnt
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 5rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }
</style>

{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}
<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div class="">
            <center>
                <h1 style="color: #15aabf">CONTACT ME</h1>
            </center>
        </div>
        <div class=" container">
            <form method="POST" action="{% url 'my_portfolio_website_app:contact_form_submit' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-4">
                        <input type="text" id="full_name" name="full_name" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Name">
                    </div>
                    <div class="form-group  col-sm-4">
                        <input type="text" id="email_id" name="email_id" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Email">
                    </div>
                    <div class="form-group col-sm-4">
                        <input type="text" id="contact_number" name="contact_number" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Contact">
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <textarea id="message" name="message" class="form-control form-control-lg border-bottom border-dark shadow-none" rows="5" placeholder="Your Message"></textarea>
                    </div>
                    <div class="col-md-12">
                        <center> <button type="submit" class="btn-info btn btn-lg">Submit</button></center>
                    </div>

                </div>
            </form>

        </div>
        <div class="container">
            <div class="icons">
                <center>
                    <a href="#"><span class="fab fa-github fa-2x"></span></a>
                    <a href="#"><i class="fab fa-linkedin fa-2x"></i></a>
                </center>

            </div>
        </div>
        <div class="container">
            <div class="copy">
                <center>
                    <h6>&copy;2020 My Portfolio</h6>
                </center>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

my_portfolio_website_app/templates/my_portfolio_website_app/users.html
{% extends 'my_portfolio_website_app/base1.html' %}
{% load static %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block headscript %}
{% endblock headscript %}


{% block content %}
<h3>All Users</h3>
<hr>
<div>
    <table id="my_table" class="display" style="width:  100%;text-align: center;">
        <thead>
            <tr>
                <th>Sr. No</th>
                <th>Username</th>
                <th>Email ID</th>
                <th>Role</th>
            </tr>
            
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.email }}</td>
                {% if user.role == 1 %}
                <td>Super Admin</td>
                {% elif user.role == 2 %}
                <td>Admin</td>
                {% else %}
                <td>Normal User</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}



{% block script %}
{% endblock  %}



{% block extrascript %}
{% endblock extrascript %}